"""add idol_applications

Revision ID: 923948737c03
Revises: 44d05545f6fa
Create Date: 2026-09-23 20:19:16.671164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923948737c03'
down_revision: Union[str, Sequence[str], None] = '44d05545f6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idol_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('social_link', sa.String(length=500), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'contacted', 'accepted', 'rejected', name='application_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idol_applications')
    # ### end Alembic commands ###
